version: '3'
volumes:
  user-data:
services:
  db_ondok:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: ondok
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: openjdk:8
    restart: always
    working_dir: /app
    volumes:
    - ../application/build/libs:/app
    - ~/.m2:/root/.m2
    expose:
    - "8080"
    command:  java -jar users-application-1.0.0-REALEASE.jar
    depends_on:
    - db_ondok
    ports:
    - "8080:8080"